[workspace]
authors = ["Mathew Biddle <mathew.biddle@noaa.gov>"]
channels = ["conda-forge"]
name = "Darwin Core Quick Checks"
platforms = ["linux-64", "osx-64", "win-64"]
version = "1.0.0"

[tasks]

[dependencies]
pandas = ">=2.3.3,<3"
requests = ">=2.32.5,<3"
nbclassic = ">=1.3.3,<2"
